name: Docker Buildx Debug
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_version: [ "3.16", "3.17", "3.18", "3.19", "3.20" ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Run Loop
        run: docker run --platform linux/arm/v7 --rm alpine:$image_version uname -m
