name: Docker Buildx Debug
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_arch:
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm/v8
          - linux/arm64
          - linux/amd64
        image_version:
          - 3.16
          - 3.20

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Output Buildx Info
        run: docker buildx ls

      - name: Docker Run Loop
        run: docker run --platform ${{ matrix.image_arch }} --rm alpine:${{ matrix.image_version }} uname -m
