name: "[buildx] Buildx Debug"
on:
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_alpine:
          - node:18.20.4-alpine3.20
          - node:20.18.0-alpine3.20
          - node:22.11.0-alpine3.20
        image_arch:
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
          - linux/amd64
        image_version:
          - 3.16
          - 3.20

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Output Buildx Info
        run: docker buildx ls

      - name: "Docker Run Loop [alpine]"
        run: docker run --rm --platform ${{ matrix.image_arch }} alpine:${{ matrix.image_version }} /bin/ash -c "/bin/uname -m"

      - name: "Docker Run Loop [node]"
        run: docker run --rm --platform ${{ matrix.image_arch }} ${{ matrix.node_alpine }} /bin/ash -c "/usr/local/bin/npm -v && /usr/local/bin/yarn -v"
